"""Read-only, detached-HEAD checkout resolution for a (repo, base_commit) pair.

Stage-4 patch generation (WP2, see
``STAGE4_PATCH_GENERATION_IMPLEMENTATION_PLAN_ZH.md`` section 5.1) needs the
FULL base-commit file text around a Stage-3 symbol's line range, so
``patch_generation.slice_prefix_suffix`` has real prefix/suffix context to cut
from -- Stage-3's ``stage3_ranked_symbols[*].code_text`` only captures the
symbol's own body, which is exactly the region ``slice_prefix_suffix``
discards (it is regenerated by the model, not context for it).

This module gets that file text by resolving a local git checkout at the
ticket's ``base_commit``. The mechanics (clone a local ``--shared
--no-checkout`` snapshot from an already-cloned repo cache, then
``checkout --detach`` the exact commit) mirror what
``scripts/run_swebench_lite_fault_localization.py``
(``resolve_repository``/``materialize_snapshot``) already does for
Stage-1/2/3 -- duplicated here as a small, independently testable module
rather than importing that script's much larger ``BatchRunConfig``, which
carries many Stage-1-only settings (embedding backend, chunk sizes, ...)
Stage-4 has no use for.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any


class RepoSnapshotError(RuntimeError):
    """Raised for every resolution failure in this module (never a raw OSError/CalledProcessError)."""


def _safe_name(value: str) -> str:
    normalized = value.replace("/", "__").replace("\\", "__").replace(":", "_")
    return "".join(char if char.isalnum() or char in "._-" else "_" for char in normalized)


def _run_git(args: list[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    completed = _run_git_process(args, cwd=cwd)
    if completed.returncode != 0:
        raise RepoSnapshotError(
            f"git {' '.join(args)} failed in {cwd}: {completed.stderr.strip() or completed.stdout.strip()}"
        )
    return completed


def _run_git_process(args: list[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    # git's own output is UTF-8 regardless of the OS locale. Without an
    # explicit encoding, `text=True` decodes with
    # locale.getpreferredencoding() -- on a Traditional Chinese Windows
    # install that is cp950, which cannot decode every byte git prints
    # (clone progress, remote messages, ...) and crashes with
    # UnicodeDecodeError instead of returning a CompletedProcess. This was
    # observed for real running scripts/prefetch_swebench_repositories.py on
    # the project's own Windows dev machine.
    return subprocess.run(
        ["git", *args], cwd=str(cwd), capture_output=True, text=True, encoding="utf-8", errors="replace", check=False
    )


def _git_output(args: list[str], *, cwd: Path, check: bool = True) -> str:
    completed = _run_git_process(args, cwd=cwd)
    if check and completed.returncode != 0:
        raise RepoSnapshotError(
            f"git {' '.join(args)} failed in {cwd}: {completed.stderr.strip() or completed.stdout.strip()}"
        )
    return completed.stdout.strip() if completed.returncode == 0 else ""


def resolve_repository_path(
    ticket: dict[str, Any],
    *,
    repo_cache_dir: Path,
    clone_missing: bool = False,
) -> Path:
    """Resolve a ticket's ``repo`` to a local, non-bare git checkout directory.

    Checks ``local_repo_path``/``repo_path``/``repository_path`` on the
    ticket first (an already-materialized checkout the caller points at
    directly), then falls back to ``<repo_cache_dir>/<safe repo name>``.
    These are the same field names
    ``scripts/run_swebench_lite_fault_localization.py`` already uses for the
    same purpose, so the same ``predictions.jsonl`` ticket rows work with
    either.
    """

    for key in ("local_repo_path", "repo_path", "repository_path"):
        value = ticket.get(key)
        if value:
            path = Path(str(value)).expanduser().resolve()
            if not path.exists():
                raise RepoSnapshotError(f"Local repository path does not exist: {path}")
            return path

    repo = str(ticket.get("repo") or "").strip()
    if not repo:
        raise RepoSnapshotError("Ticket does not include a 'repo' field or a local repository path.")
    repo_path = (Path(repo_cache_dir) / _safe_name(repo)).resolve()
    if repo_path.exists():
        return repo_path
    if not clone_missing:
        raise RepoSnapshotError(
            f"Repository cache is missing for {repo}: {repo_path}. Pass clone_missing=True to clone it, "
            "or prefetch it first (see scripts/prefetch_swebench_repositories.py)."
        )
    repository_url = str(ticket.get("repository_url") or f"https://github.com/{repo}")
    repo_path.parent.mkdir(parents=True, exist_ok=True)
    _run_git(["clone", "--no-checkout", repository_url, str(repo_path)], cwd=repo_path.parent)
    return repo_path


def _resolve_commit(repo_path: Path, base_commit: str, *, fetch_missing: bool) -> str:
    resolved = _git_output(["rev-parse", "--verify", f"{base_commit}^{{commit}}"], cwd=repo_path, check=False)
    if not resolved and fetch_missing:
        _run_git(["fetch", "--all", "--tags"], cwd=repo_path)
        resolved = _git_output(["rev-parse", "--verify", f"{base_commit}^{{commit}}"], cwd=repo_path, check=False)
    if not resolved:
        raise RepoSnapshotError(f"base_commit is unavailable in {repo_path}: {base_commit}")
    return resolved


def materialize_commit_snapshot(
    source_repo: Path,
    *,
    repo: str,
    base_commit: str,
    snapshot_cache_dir: Path,
    fetch_missing_commits: bool = False,
) -> Path:
    """Return a detached-HEAD checkout of ``source_repo`` at ``base_commit``.

    Reuses an existing snapshot under ``snapshot_cache_dir`` when one already
    sits at the right commit, so repeated runs across many tickets that share
    a (repo, base_commit) pair (common within one Stage-4 pilot) do not
    re-clone. The snapshot is a ``--shared`` clone (fast, shares the object
    store with ``source_repo`` -- no extra disk for blobs) checked out
    ``--detach`` so nothing here can accidentally move a real branch in
    ``source_repo``.
    """

    source_repo = Path(source_repo)
    if not (source_repo / ".git").exists():
        raise RepoSnapshotError(f"Not a non-bare git checkout: {source_repo}")
    if not base_commit:
        raise RepoSnapshotError("base_commit must be non-empty.")

    resolved_commit = _resolve_commit(source_repo, base_commit, fetch_missing=fetch_missing_commits)
    snapshot_path = (Path(snapshot_cache_dir) / f"{_safe_name(repo)}__{resolved_commit[:16]}").resolve()
    if snapshot_path.exists():
        existing_head = _git_output(["rev-parse", "HEAD"], cwd=snapshot_path, check=False)
        if existing_head == resolved_commit:
            return snapshot_path
        raise RepoSnapshotError(f"Snapshot path exists at the wrong commit: {snapshot_path}")

    snapshot_path.parent.mkdir(parents=True, exist_ok=True)
    _run_git(["clone", "--shared", "--no-checkout", str(source_repo), str(snapshot_path)], cwd=snapshot_path.parent)
    _run_git(["checkout", "--detach", resolved_commit], cwd=snapshot_path)
    return snapshot_path


def read_file_text(snapshot_path: Path, file_path: str) -> str:
    """Read one file's text out of a materialized commit snapshot.

    Raises ``RepoSnapshotError`` (never a raw ``OSError``) so batch callers
    can catch a single exception type for every resolution failure in this
    module -- one bad ticket's missing/unreadable file should not crash a
    whole Stage-4 batch run.
    """

    snapshot_root = Path(snapshot_path).resolve()
    full_path = (snapshot_root / file_path).resolve()
    try:
        full_path.relative_to(snapshot_root)
    except ValueError:
        raise RepoSnapshotError(f"file_path escapes the repository snapshot: {file_path!r}") from None

    try:
        return full_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise RepoSnapshotError(f"Could not read {file_path} from snapshot {snapshot_path}: {exc}") from None
